# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# Copyright (C) 2019  Marcus Rickert
#
# See https://github.com/marcus67/little_brother
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# See https://stackoverflow.com/questions/26811089/vagrant-how-to-have-host-platform-specific-provisioning-steps
module OS
    def OS.windows
        (/cygwin|mswin|mingw|bccwin|wince|emx/ =~ RUBY_PLATFORM) != nil
    end

    def OS.mac
        (/darwin/ =~ RUBY_PLATFORM) != nil
    end

    def OS.unix
        !OS.windows
    end

    def OS.linux
        OS.unix and not OS.mac
    end
end

require './settings.rb'

# Require the reboot plugin.
#require './assets/vagrant-provision-reboot-plugin'


# VM Settings
VAGRANT_HOME_PARTITION_FILE="drives/home.dvi"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = VAGRANT_BOX
  config.vm.box_version = VAGRANT_BOX_VERSION
  config.ssh.insert_key = false

  config.vm.provider :virtualbox do |vb,override|
    vb.name = VM_NAME
    vb.gui = true

    vb.memory = VM_MEMORY
    vb.cpus = VM_CPUS

    # Siehe http://stackoverflow.com/questions/24231620/how-to-set-vagrant-virtualbox-video-memory
    vb.customize ["modifyvm", :id, "--vram", VM_VRAM]

    # enable shared clipboard and drag'n'drop
    vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    vb.customize ["modifyvm", :id, "--draganddrop", "bidirectional"]

    override.vm.network "private_network", :type => 'dhcp', :adapter => 2
  end

  # Create groups and users "seth" and "jennifer" ein
  config.vm.provision "shell", path: "assets/setup-users.sh"

end
