"""add downtime attributes

Revision ID: 96ff8f93ef32
Revises: 2f458b3a313e
Create Date: 2019-10-02 23:57:08.792919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96ff8f93ef32'
down_revision = '2f458b3a313e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_event', sa.Column('downtime', sa.Integer(), server_default='0', nullable=True))
    op.add_column('process_info', sa.Column('downtime', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('process_info', 'downtime')
    op.drop_column('admin_event', 'downtime')
    # ### end Alembic commands ###
