{
 "title": "LittleBrother",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Instance",
    "query": "little-brother-prod, little-brother-test, little-brother-feature-test"
   }
  ]
 },
 "panels": [
  {
   "title": "Config'ed Users",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(little_brother_configured_users{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Monit'ed Users",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 0 },
   "targets": [
    {
     "expr": "little_brother_monitored_users{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "sum(little_brother_active_users{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "little_brother_active_users{job=\"$job\"}",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Nodes (Uptime)",
   "type": "table",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "little_brother_uptime{job=\"$job\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Master Node (Versions and Revisions)",
   "type": "text",
   "gridPos": { "h": 1, "w": 6, "x": 18, "y": 0 }
  },
  {
   "title": "Python",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "python_info{job=\"$job\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "App Version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "little_brother_system_info{job=\"$job\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "App Revision",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "little_brother_system_info{job=\"$job\"}",
     "legendFormat": "{{revision}}"
    }
   ]
  },
  {
   "title": "Monitored Devices",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(little_brother_monitored_devices{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Active Devices",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 5 },
   "targets": [
    {
     "expr": "sum(little_brother_active_devices{job=\"$job\"}) "
    }
   ]
  },
  {
   "title": "Active Devices",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "little_brother_active_devices{job=\"$job\"}",
     "legendFormat": "{{devicename}}"
    }
   ]
  },
  {
   "title": "Moving Average Response Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "little_brother_device_moving_average_response_time{job=\"$job\"}",
     "legendFormat": "{{devicename}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "little_brother_device_response_time{job=\"$job\"}",
     "legendFormat": "{{devicename}}"
    }
   ]
  },
  {
   "title": "Monitored Hosts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(little_brother_monitored_hosts{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Monitored Hosts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "little_brother_monitored_hosts{job=\"$job\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Forced Logouts (per minute)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(little_brother_forced_logouts_total{job=\"$job\"}[1m])",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "delta(process_cpu_seconds_total{job=\"$job\"}[5m])/3",
     "legendFormat": "master"
    },
    {
     "expr": "delta(node_process_cpu_seconds_total{job=\"$job\"}[5m])/3",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Resident Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$job\"}",
     "legendFormat": "master"
    },
    {
     "expr": "node_process_resident_memory_bytes{job=\"$job\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Request Duration by Service (per minute)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (service) (delta(little_brother_http_requests_sum{job=\"$job\"}[1m])) / sum by (service) (delta(little_brother_http_requests_count{job=\"$job\"}[1m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Request Count by Service (per minute)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (service) (delta(little_brother_http_requests_count{job=\"$job\"}[1m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Request Count by Service (last hour)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 11, "y": 17 },
   "targets": [
    {
     "expr": "sum by (service) (delta(little_brother_http_requests_count{job=\"$job\"}[1h]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Request Count by Hostname (per minute)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (hostname) (delta(little_brother_http_requests_count{job=\"$job\"}[1m]))",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Request Count by Hostname (last hour)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 17 },
   "targets": [
    {
     "expr": "sum by(hostname) (delta(little_brother_http_requests_count{job=\"$job\"}[1h]))",
     "legendFormat": "{{hostname}}"
    }
   ]
  }
 ]
}