"""add max_activity_duration

Revision ID: 2f458b3a313e
Revises: 647cf46033a9
Create Date: 2019-09-14 23:57:48.727729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f458b3a313e'
down_revision = '647cf46033a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rule_override', sa.Column('max_activity_duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rule_override', 'max_activity_duration')
    # ### end Alembic commands ###
