"""add uid_mapping

Revision ID: 8802c76063af
Revises: ed5e0310d209
Create Date: 2024-03-03 00:34:29.499898

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '8802c76063af'
down_revision = 'ed5e0310d209'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uid_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('server_group', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('uid_mapping', schema=None) as batch_op:
        batch_op.create_unique_constraint('uid_server_group', ('uid', 'server_group'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uid_mapping')
    # ### end Alembic commands ###
