"""issue-169

Revision ID: a271817b1d64
Revises: 9713cef84918
Create Date: 2022-03-24 19:44:00.724780

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a271817b1d64'
down_revision = '9713cef84918'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user2device', sa.Column('blockable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user2device', 'blockable')
    # ### end Alembic commands ###
