"""prohibited_process_name_pattern

Revision ID: e0c0d7048235
Revises: 0a5c7b6ad27a
Create Date: 2021-05-24 23:16:21.270325

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e0c0d7048235'
down_revision = '0a5c7b6ad27a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('prohibited_process_name_pattern', sa.String(length=4096), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'prohibited_process_name_pattern')
    # ### end Alembic commands ###
