"""blocked_urls at device level

Revision ID: ed5e0310d209
Revises: a271817b1d64
Create Date: 2022-06-19 13:27:26.938827

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ed5e0310d209'
down_revision = 'a271817b1d64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('blocked_urls', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'blocked_urls')
    # ### end Alembic commands ###
